"""Run the backtest on the built warehouse and write results to forecast/results/ (SYNTHETIC data).

Usage: python -m forecast.run   (requires `make build`)
Outputs (gitignored CSVs, consumed by the dashboard): backtest_forecasts.csv, backtest_mape.csv,
backtest_by_horizon.csv, forward_forecast.csv. Also writes forecast/RESULTS.md.
"""

from __future__ import annotations

import json
from pathlib import Path

import duckdb
import numpy as np
import pandas as pd

from data_gen.load import DEFAULT_PATH

from .model import (
    FIRST_ORIGIN,
    HORIZON,
    MODELS,
    backtest,
    compare_models,
    forward_forecast,
    interval_coverage,
    mape,
    score,
    small_denominator_report,
    smape,
    wape,
)

ROOT = Path(__file__).resolve().parent
RESULTS_DIR = ROOT / "results"

FORECASTS_COLUMNS = [
    "retailer_id", "origin_month", "target_month", "horizon", "actual", "mase_scale", *MODELS,
]  # fmt: skip
MAPE_COLUMNS = ["retailer_id", "model", "mape", "smape", "mase", "wape", "n_forecasts"]
FORWARD_COLUMNS = [
    "retailer_id", "month", "seasonal_naive", "holt_winters", "hw_p10", "hw_p90",
]  # fmt: skip

MONTHLY_SQL = """
    select retailer_id, deduction_month, sum(deduction_amount) as amount
    from metrics.m_deductions_monthly
    where not is_burn_in_month
    group by retailer_id, deduction_month
"""


def load_monthly(con: duckdb.DuckDBPyConnection) -> pd.DataFrame:
    """Monthly deduction dollars, one column per retailer, ramp-up months excluded, gaps = 0."""
    long = con.execute(MONTHLY_SQL).df()
    long["deduction_month"] = pd.to_datetime(long["deduction_month"])
    wide = long.pivot(index="deduction_month", columns="retailer_id", values="amount")
    full = pd.date_range(wide.index.min(), wide.index.max(), freq="MS")
    return wide.reindex(full).fillna(0.0).astype(float).sort_index(axis=1)


def _short(path: Path) -> Path:
    return path.relative_to(ROOT.parent) if path.is_relative_to(ROOT.parent) else path


def mase_pooled(frame: pd.DataFrame, model: str) -> float:
    return float((np.abs(frame["actual"] - frame[model]) / frame["mase_scale"]).mean())


def by_horizon(forecasts: pd.DataFrame) -> pd.DataFrame:
    complete = forecasts.dropna(subset=list(MODELS))
    rows = []
    for horizon, group in complete.groupby("horizon"):
        for model in MODELS:
            a, f = group["actual"].to_numpy(), group[model].to_numpy()
            rows.append(
                {"horizon": horizon, "model": model, "mape": mape(a, f), "wape": wape(a, f)}
            )
    return pd.DataFrame(rows)


def write_report(
    forecasts: pd.DataFrame, scores: pd.DataFrame, horizons: pd.DataFrame, path: Path, extra: dict
):
    wide = scores.pivot(index="retailer_id", columns="model", values="mape")
    complete = forecasts.dropna(subset=list(MODELS))
    pooled = {m: mape(complete["actual"].to_numpy(), complete[m].to_numpy()) for m in MODELS}
    pooled_w = {m: wape(complete["actual"].to_numpy(), complete[m].to_numpy()) for m in MODELS}
    hw_wins = int((wide["holt_winters"] < wide["seasonal_naive"]).sum())
    failed = int(forecasts["holt_winters"].isna().sum())
    worse = wide[wide["holt_winters"] >= wide["seasonal_naive"]]
    lines = [
        "# Forecast backtest results (SYNTHETIC data)",
        "",
        "Generated by `python -m forecast.run`; do not edit by hand. Target: monthly deduction dollars by",
        "retailer (deduction-date basis, ramp-up months excluded). Rolling-origin, expanding window, first origin",
        f"after {FIRST_ORIGIN} training months, horizon {HORIZON} months, {len(forecasts) // (12 * HORIZON)} origins.",
        "",
        "## Headline",
        "",
        f"- Pooled MAPE: seasonal naive **{pooled['seasonal_naive']:.1%}**, Holt-Winters **{pooled['holt_winters']:.1%}**.",
        f"- Pooled WAPE: seasonal naive {pooled_w['seasonal_naive']:.1%}, Holt-Winters {pooled_w['holt_winters']:.1%}.",
        f"- Holt-Winters had the lower MAPE for **{hw_wins} of {len(wide)}** retailers.",
        f"- Holt-Winters fits that failed (excluded from scoring for both models): {failed}.",
        "",
        "## MAPE by retailer",
        "",
        "| Retailer | Seasonal naive | Holt-Winters | Better |",
        "|---|---|---|---|",
    ]
    for rid, row in wide.iterrows():
        better = "Holt-Winters" if row["holt_winters"] < row["seasonal_naive"] else "Seasonal naive"
        lines.append(
            f"| {rid} | {row['seasonal_naive']:.1%} | {row['holt_winters']:.1%} | {better} |"
        )
    lines += [
        "",
        "## MAPE by forecast horizon (pooled)",
        "",
        "| Horizon (months) | Seasonal naive | Holt-Winters |",
        "|---|---|---|",
    ]
    for h, grp in horizons.pivot(index="horizon", columns="model", values="mape").iterrows():
        lines.append(f"| {h} | {grp['seasonal_naive']:.1%} | {grp['holt_winters']:.1%} |")
    comp, cov, small = extra["comparison"], extra["coverage"], extra["small_denominators"]
    verdict = (
        "a statistical tie"
        if comp["boot_ci_low"] <= 0 <= comp["boot_ci_high"] and comp["dm_hln_p_value"] > 0.05
        else "a measurable difference"
    )
    lines += [
        "",
        "## Is Holt-Winters really better than the baseline?",
        "",
        f"Resampling the {comp['n_origins']} forecast origins (not the points: points within an origin are correlated), "
        f"the pooled MAPE advantage of Holt-Winters is {comp['mean_diff_mape'] * 100:.2f} points "
        f"(bootstrap 95% CI {comp['boot_ci_low'] * 100:.2f} to {comp['boot_ci_high'] * 100:.2f}; bootstrap p = {comp['boot_p_value']:.2f}).",
        f"Diebold-Mariano with the Harvey-Leybourne-Newbold correction: t = {comp['dm_hln_statistic']:.2f}, p = {comp['dm_hln_p_value']:.2f} "
        f"({comp['n_origins']} origins, so low power). Holt-Winters is better at {comp['origins_hw_better']} of {comp['n_origins']} origins "
        f"and for {comp['retailers_hw_better']} of {comp['retailers']} retailers (sign test p = {comp['sign_test_p_value']:.2f}).",
        f"**Verdict: {verdict}.**",
        "",
        "## Error metrics beyond MAPE (pooled)",
        "",
        "| Model | MAPE | sMAPE | MASE | WAPE |",
        "|---|---|---|---|---|",
    ]
    for m in MODELS:
        a, f_ = complete["actual"].to_numpy(), complete[m].to_numpy()
        lines.append(
            f"| {m} | {pooled[m]:.1%} | {smape(a, f_):.1%} | {mase_pooled(complete, m):.2f} | {pooled_w[m]:.1%} |"
        )
    lines += [
        "",
        "MASE is scaled by the seasonal-naive in-sample error of each fold, so 1.0 means 'no better than the "
        "baseline would have been on its own training data'.",
        "",
        "## MAPE and small denominators",
        "",
        f"Seasonal-naive errors for the 3 smallest retailers (by mean monthly deductions): MAPE {small['smallest_3']['mape']:.1%}, "
        f"sMAPE {small['smallest_3']['smape']:.1%}, WAPE {small['smallest_3']['wape']:.1%}; for the 3 largest: MAPE "
        f"{small['largest_3']['mape']:.1%}, sMAPE {small['largest_3']['smape']:.1%}, WAPE {small['largest_3']['wape']:.1%}. "
        f"Correlation between log(actual) and absolute percentage error: {small['corr_log_actual_vs_ape']:.2f}. "
        "No retailer-month is near zero here, so MAPE does not explode, but small retailers' percentage errors are "
        "much larger than large retailers'. WAPE and MASE weight errors by size (and are more relevant to a dollar "
        "forecast); MAPE is shown because the brief asked for it.",
        "",
        "## Prediction-interval coverage",
        "",
        f"The dashboard band is the {cov['nominal']:.0%} band of pooled actual/forecast ratios. Coverage on the same backtest "
        f"it was fitted on: {cov['in_sample_coverage']:.1%} (about nominal by construction). Honest out-of-sample coverage, with each "
        f"origin's band built only from earlier origins ({cov['out_of_sample_points']} points): **{cov['out_of_sample_coverage']:.1%}**.",
    ]
    lines += ["", "## Where the model fails or loses", ""]
    if len(worse):
        names = ", ".join(str(r) for r in worse.index)
        lines.append(f"- Holt-Winters did **not** beat the baseline for retailers: {names}.")
        gap = (worse["holt_winters"] - worse["seasonal_naive"]).idxmax()
        lines.append(
            f"- Largest loss: retailer {gap} (Holt-Winters {worse.loc[gap, 'holt_winters']:.1%} vs "
            f"baseline {worse.loc[gap, 'seasonal_naive']:.1%})."
        )
    else:
        lines.append("- Holt-Winters beat the baseline for every retailer on MAPE.")
    worst = wide["holt_winters"].idxmax()
    lines.append(
        f"- Hardest series for Holt-Winters: retailer {worst} at {wide.loc[worst, 'holt_winters']:.1%} MAPE."
    )
    lines += [
        "",
        "## Caveats (read before trusting any of this)",
        "",
        f"- Only {len(forecasts) // (12 * HORIZON)} overlapping origins x {HORIZON} horizons per retailer: the folds are not independent, so a",
        "  small MAPE gap between models is within noise.",
        "- 24 training months is the minimum for a seasonal model (two cycles); Holt-Winters estimates well over a",
        "  dozen parameters from them (smoothing, damping, 12 initial seasonal values).",
        "- The data are synthetic with a smooth, known multiplicative seasonal pattern and a one-off anomaly; real",
        "  deduction series are lumpier (audits, policy changes), so these errors are optimistic.",
        "- Monthly dollars by retailer are small-sample series (the smallest retailers have far fewer deductions per",
        "  month), which inflates MAPE for them.",
        "- Retailer 5 carries the generator's one-off shortage spike (Apr-May 2025, pattern 7). That is a plausible",
        "  reason it is hard to forecast, but it was not isolated by an experiment.",
        "- The prediction interval in `forward_forecast.csv` is empirical (pooled backtest error quantiles), not",
        "  model-based, and assumes future errors look like past errors.",
    ]
    path.write_text("\n".join(lines) + "\n")


def main(
    warehouse: Path = DEFAULT_PATH,
    out_dir: Path = RESULTS_DIR,
    report_path: Path = ROOT / "RESULTS.md",
) -> None:
    con = duckdb.connect(str(warehouse), read_only=True)
    monthly = load_monthly(con)
    con.close()
    forecasts = backtest(monthly)
    scores = score(forecasts)
    horizons = by_horizon(forecasts)
    forward = forward_forecast(monthly, forecasts)
    out_dir.mkdir(parents=True, exist_ok=True)
    forecasts[FORECASTS_COLUMNS].to_csv(out_dir / "backtest_forecasts.csv", index=False)
    scores[MAPE_COLUMNS].to_csv(out_dir / "backtest_mape.csv", index=False)
    horizons.to_csv(out_dir / "backtest_by_horizon.csv", index=False)
    forward[FORWARD_COLUMNS].to_csv(out_dir / "forward_forecast.csv", index=False)
    extra = {
        "comparison": compare_models(forecasts),
        "coverage": interval_coverage(forecasts),
        "small_denominators": small_denominator_report(forecasts),
    }
    (out_dir / "comparison.json").write_text(json.dumps(extra, indent=1) + "\n")
    write_report(forecasts, scores, horizons, report_path, extra)
    pooled = {
        m: mape(forecasts.dropna()["actual"].to_numpy(), forecasts.dropna()[m].to_numpy())
        for m in MODELS
    }
    print(
        f"months={len(monthly)} folds={len(forecasts)} pooled MAPE: "
        + ", ".join(f"{m}={v:.3f}" for m, v in pooled.items())
    )
    print(f"wrote {_short(out_dir)} and {_short(report_path)}")


if __name__ == "__main__":
    main()
