"""Regenerate PLANTED_PATTERNS.md: planted target vs the value OBSERVED in the generated data."""

from __future__ import annotations

import tempfile
from pathlib import Path

import duckdb

from data_gen import measures as m
from data_gen.config import PROBLEM_SKUS, Config
from data_gen.generate import generate
from data_gen.load import build_warehouse
from warehouse.validate import findings

OUT = Path(__file__).resolve().parents[1] / "PLANTED_PATTERNS.md"

HEADER = """# Planted patterns (SYNTHETIC data)

> All data here is synthetic and generated by `data_gen/`. It is not Confido's data or schema.

Each pattern is drawn from a distribution (per-retailer random effects, lognormal noise), so the
effect is visible but imperfect. Tests in `tests/test_generator.py` assert the **range** column;
the **observed** column below is produced by `scripts/pattern_report.py` from the actual generator
run (seed {seed}). Do not edit the table by hand: rerun `make patterns`.

| # | Pattern | Where | Target | Test range | Observed |
|---|---|---|---|---|---|
"""

FOOTER = """
## Mechanisms

1. **Retailer A fines.** Retailer A's per-invoice probability of a compliance fine is the peer base
   rate times a lognormal multiplier (median 3, sigma 0.12); peers get their own lognormal noise
   (sigma 0.25). 85% of A's invoices carry SKUs {p1} and {p2}, and 80% of A's attributable fines
   on those invoices point at one of them. About 20% of fines have no SKU (unattributed).
2. **Promo spike.** For invoices dated Oct-Dec, promo-deduction probability is multiplied by a
   per-retailer-year lognormal (median 2.4, sigma 0.25) and the claim lag is 45-90 days, so the
   deductions land in Dec-Mar. Promo disputes are filed ~6% of the time. Jan-Feb 2023 has no
   prior Q4 in the data, so the spike is measured in 2024 and 2025.
3. **Shortage recovery.** Shortage deductions are disputed ~18% of the time and won (full or
   partial) ~80% of resolved disputes; other reasons are disputed 30-40% and win 45-65%. Win
   probability also falls with filing lag (x1.10 within 14 days, down to x0.65 beyond 60 days).
4. **Retailer B lag.** From 2025-01-01, Retailer B's payment delay ramps up ~12 days over ~6 months
   (invoice-date based) and then plateaus; noise sigma is 4 days.
5. **Seasonality and growth.** Monthly multipliers (Q4 peak, summer dip) times 8% yearly growth,
   with 3% monthly noise and Poisson invoice counts.
6. **Dirty load.** `raw_dirty` is an unconstrained copy of the clean tables with a known set of
   defects injected (see table). A duplicate payment also overpays its invoice, so the same three
   invoices are reported again under the reconciliation rule.
7. **One-off shortage anomaly (extra, for anomaly-detection tests).** Retailer E's shortage
   probability is multiplied by 5 for invoices dated 2025-04, so its shortage deductions spike in
   Apr-May 2025.

## Known limitations of the patterns

- Right-censoring: deductions and payments after the as-of date (2025-12-31) are not in the data,
  so late invoice months look cleaner than they will end up. Analyses account for this explicitly.
- Left-censoring: there are no 2022 invoices, so deduction-date months Jan-Mar 2023 are
  under-populated (a ramp-up artefact of the generator, not a business effect).
"""


def row(n, name, where, target, rng, observed) -> str:
    return f"| {n} | {name} | {where} | {target} | {rng} | {observed} |\n"


def main() -> None:
    cfg = Config()
    t = generate(cfg)
    attributed, top2 = m.fine_top2_share(t, attributed_only=True)
    overall, _ = m.fine_top2_share(t, attributed_only=False)
    s_disp, s_win = m.dispute_stats(t, "shortage")
    o_disp, o_win = m.dispute_stats(t, "shortage", invert=True)
    slopes = m.lag_slopes(t)
    growth, q4 = m.revenue_growth_and_seasonality(t)
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / "w.duckdb"
        build_warehouse(path, cfg)
        con = duckdb.connect(str(path), read_only=True)
        dirty, clean = findings(con, "raw_dirty"), findings(con, "raw")
        con.close()

    body = HEADER.format(seed=cfg.seed)
    body += row(1, "Retailer A compliance fines ~3x peers", "compliance_fine, retailer 1",
                "~3.0x peer median fine $/revenue", "2.2-4.0x",
                f"{m.fine_ratio_a_vs_peers(t):.2f}x")  # fmt: skip
    body += row("1b", "...concentrated in 2 SKUs", "retailer 1 fines by SKU",
                f"top-2 = SKUs {PROBLEM_SKUS[0]}, {PROBLEM_SKUS[1]}, ~70% of attributed fines",
                "top-2 share of attributed >= 55%; of all (incl. unattributed) >= 40%",
                f"top-2 = {sorted(top2)}; attributed {attributed:.1%}; all {overall:.1%} "
                f"(unattributed dilutes it by {100 * (attributed - overall):.1f} pts)")  # fmt: skip
    body += row(2, "Promo spike after Q4, rarely disputed", "promo deductions, Jan-Feb 2024/25",
                "Jan-Feb monthly $ ~2x Mar-Sep; dispute rate ~6%", ">= 1.5x; dispute rate <= 15%",
                f"{m.promo_spike_ratio(t):.2f}x; dispute rate {m.promo_dispute_rate(t):.1%}")  # fmt: skip
    body += row(3, "Shortage: high win, low dispute", "shortage vs other reasons",
                "dispute ~18%, win ~80% (others ~26% / ~54%)",
                "win 65-92%; dispute 8-30%; win gap >= 8 pts; dispute < others",
                f"shortage dispute {s_disp:.1%}, win {s_win:.1%}; others {o_disp:.1%} / {o_win:.1%}")  # fmt: skip
    body += row(4, "Retailer B payment lag drifts up", "retailer 2, invoice months 2025-01..06",
                "~+12 days over 6 months (~2 days/month)",
                "B slope >= 1.0 d/month; peers abs(slope) <= 1.0; rise >= 5 d",
                f"B slope {slopes[2]:.2f} d/month; peers within [{slopes.drop(2).min():.2f}, "
                f"{slopes.drop(2).max():.2f}]; B rise Jan->Q2 {m.lag_rise_b(t):.1f} d")  # fmt: skip
    body += row(5, "Seasonality + growth", "all invoices", "~8% YoY; Q4 ~1.17x other months",
                "growth 4-12%; Q4 ratio 1.1-1.5", f"growth {growth:.1%}; Q4 ratio {q4:.2f}")  # fmt: skip
    body += row(6, "Dirty load defects", "raw_dirty",
                "3 orphaned deductions, 3 duplicate payments (+3 overpaid invoices), 3 negative amounts",
                "validator finds exactly these; clean load finds none",
                f"dirty findings {dirty}; clean findings {clean or 'none'}")  # fmt: skip
    body += row(7, "One-off shortage anomaly (extra)", "retailer 5, shortage, Apr-May 2025",
                "peak month well above its own median", "peak/median >= 2.0",
                f"{m.anomaly_cell(t):.2f}x")  # fmt: skip
    OUT.write_text(body + FOOTER.format(p1=PROBLEM_SKUS[0], p2=PROBLEM_SKUS[1]))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
